name: Weekly scheduling
on:
  schedule:
    - cron:  '20 9 * * WED'
  workflow_dispatch:
jobs:
  scheduling:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
    - name: scheduling
      id: scheduling
      run: |
        index=$(ruby scheduler.rb)
        echo "::set-output name=CURRENT_INDEX::${index}"
    - name: Commit new schedule
      run: |
        if ! git diff --exit-code --quiet
        then
          git add schedule.json
          git config --local user.email "yshoji@launchableinc.com"
          git config --local user.name "yoshiori"
          git commit -m "Update schedule.json"
          git push origin main
        fi
    - name: Notify current
      run: |
        assignee=$(cat schedule.json | jq -r .[${{ steps.scheduling.outputs.CURRENT_INDEX }}].assignee)
        start=$(cat schedule.json | jq -r .[${{ steps.scheduling.outputs.CURRENT_INDEX }}].start)
        end=$(cat schedule.json | jq -r .[${{ steps.scheduling.outputs.CURRENT_INDEX }}].end)
        echo $assignee
        echo $start
        echo $end
